name: On PR Open
on:
  pull_request:
    types: [opened]
jobs:
  jobOne:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Name
        id: vars
        run: echo ::set-output name=branch::${GITHUB_HEAD_REF}
      - name: Build and push to ECR
        run: echo "Pushed image to ECR"
      - name: Call Unit Tests
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: mab8192/YTPredictor
          event-type: unit-tests
          client-payload: '{"ref": "${{ steps.vars.outputs.branch }}"}'
