name: Repository Dispatch
on:
  repository_dispatch:
    types: [dev-deploy]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The source branch is ${{ github.event.client_payload.ref }}"
