name: Unit Tests
on:
  pull_request:
  repository_dispatch:
    types: [unit-tests]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Name on PR
        id: vars
        run: echo ::set-output name=branch::${GITHUB_HEAD_REF}
        if: github.event_name == 'pull_request'
      - name: Set Branch Name on Dispatch
        id: vars
        run: echo ::set-output name=branch::${{ github.event.client_payload.ref }}
        if: github.event_name == 'repository_dispatch'
      - name: Pull image from ECR
        run: echo "Pulled image tagged with branch name ${{ steps.vars.outputs.branch }}"
      - name: Re-tag image as local
        run: echo "Tagged image as local."
      - name: Run Tests
        run: echo "Tests Passed!"
